#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun  2 20:30:52 2020

@author: ekhahm
"""

import random

def dice_rand():
    dice1 = random.randrange(1,7,1)
    dice2 = random.randrange(1,7,1)
    return dice1, dice2

for i in range(1000):
    result = dice_rand()
    if result[0] == result[1]:
        print("identical")
    else:
        print("not identical")
    i+=1